FROM node:hydrogen as dependencies

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install -g npm@10.8.2 && npm ci

FROM node:hydrogen as development
WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
ENV NODE_ENV development

EXPOSE 3000
CMD ["npm", "run", "dev"]